import React from "react";
import './TermsAndConditions.css';

const TermsAndConditions = () => {
  return (
    <div className="min-h-screen bg-gray-100 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-md p-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms and Conditions</h1>

        <div className="space-y-6">
          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-4">General</h2>
            <div className="space-y-4 text-gray-600">
              <p>a) This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
              <p>b) This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.helah.in.</p>
              <p>c) The domain name www.helah.in ("Website"), is owned and operated by Gehna Gems India Pvt. Ltd. ("Company") a Private Company limited by shares, incorporated under the provisions of the Companies Act, 2013, and having its registered Bengaluru where such expression shall, unless repugnant to the context thereof, be deemed to include its respective representatives, administrators, employees, directors, officers, agents and their successors and assigns.</p>
              <p>d) For the purpose of these Terms of Use ("Terms"), wherever the context so requires,</p>
              <ul className="list-disc pl-6">
                <li>The term 'You', 'Your' & 'User' shall mean any legal person or entity accessing or using the services provided on this Website</li>
                <li>The terms 'We', 'Us' & 'Our' shall mean the Website www.helah.in and/or the Company Gehna Gems India Pvt. Ltd</li>
                <li>The terms 'Party' & 'Parties' shall respectively be used to refer to the User and the Company individually and collectively  as the context so requires.               </li>
              </ul>
              <p>


              e) The headings of each section in these Terms are only for the purpose of organizing the various provisions under these Terms in an orderly manner, and shall not be used by either Party to interpret the provisions contained herein in any manner. Further, it is specifically agreed to by the Parties that the headings shall have no legal or contractual value.
<br /> <br />
f) The use of the Website by the User is solely governed by these Terms as well as the Privacy Policy (“Policy”, available at <a className="text-blue-500" href="http://www.helah.in/privacypolicy">http://www.helah.in/privacypolicy</a> ), and any modifications or amendments made thereto by the Company from time to time, at its sole discretion. Visiting the home page of the Website and/or using any of the services provided on the Website shall be deemed to signify the User’s unequivocal acceptance of these Terms and the aforementioned Policy, and the User expressly agrees to be bound by the same. The User expressly agrees and acknowledges that the Terms and Policy are co-terminus, and that expiry / termination of either one will lead to the termination of the other, save as provided in Section 3 hereunder.
<br /> <br />

g) The User unequivocally agrees that these Terms and the aforementioned Policy constitute a legally binding agreement between the User and the Company, and that the User shall be subject to the rules, guidelines, policies, terms, and conditions applicable to any service that is provided by the Website, and that the same shall be deemed to be incorporated into these Terms, and shall be treated as part and parcel of the same. The User acknowledges and agrees that no signature or express act is required to make these Terms and the Policy binding on the User, and that the User’s act of visiting the any part of the Website constitutes the User’s full and final acceptance of these Terms and the aforementioned Policy.
<br /> <br />

h) The Company reserves the sole and exclusive right to amend or modify these Terms without any prior permission or intimation to the User, and the User expressly agrees that any such amendments or modifications shall come into effect immediately. The User has a duty to periodically check the terms and stay updated on its requirements. If the User continues to use the Website following such a change, the User will be deemed to have consented to any and all amendments / modifications made to the Terms. In so far as the User complies with these Terms, he/she is granted a personal, non-exclusive, non-transferable, revocable, limited privilege to enter and use the Website.

<br /> <br />

              </p>
            </div>
          </section>

          <section className="space-y-8 mt-10">
            <div>
              <h2 className="text-2xl font-bold mb-2">Eligibility</h2>
              <p className="text-base text-gray-700">
                The User represents and warrants that he/she is competent and eligible to enter into legally binding agreements and that he/she has the requisite authority to bind himself/herself to these Terms, as determined solely by the provisions of the Indian Contract Act, 1872. The User may not use this Website if he/she is not competent to contract under the Indian Contract Act, 1872, or is disqualified from doing so by any other applicable law, rule or regulation currently in force.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold mb-2">Term</h2>
              <p className="text-base text-gray-700">
                These Terms shall continue to form a valid and binding contract between the Parties, and shall continue to be in full force and effect until:
                <br />a) The User continues to access and use the Website; or
                <br />b) The Transaction between the Parties, if any, concludes to the satisfaction of both Parties;
                <br />Whichever is longer.
                <br />
                The Parties agree that certain portions of these Terms (“Sections”), such as Sections 13, 14, 15 & 17, shall continue to remain in full force and effect indefinitely, even after the expiry or termination of these Terms as contemplated herein.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold mb-2">Termination</h2>
              <p className="text-base text-gray-700">
                The Company has created a platform which showcases a collection of ready-to-wear precious and semi-precious jewellery that exhibits a fresh marriage of the classic and contemporary styles, and could very well be your jewellery indulgences from time to time. All jewellery showcased on the Website are our individual and unique creation.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold mb-2">Communication</h2>
              <p className="text-base text-gray-700">
                By using this Website, and providing his/her contact information to the Company through the Website, the User hereby agrees and consents to receiving calls, autodialed and/or pre-recorded message calls, e-mails and SMSs from the Company and/or any of its affiliates or partners at any time, subject to the Policy. In the event that the User wishes to stop receiving any such marketing or promotional calls / email messages / text messages, the User may send an e-mail to the effect to <span className="font-medium">customercare@helah.in</span> with the subject <span className="font-medium">[Do not Disturb]</span>. The User agrees and acknowledges that it may take up to seven (7) business days for the Company to give effect to such a request by the User.
                <br /><br />
                The User expressly agrees that notwithstanding anything contained hereinabove, he/she may be contacted by the Company or any of its affiliates / partners relating to any service availed of by the User on the Website or anything pursuant there to.
                <br /><br />
                It is expressly agreed to by the Parties that any information shared by the User with the Company shall be governed by the Policy.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold mb-2">Charges</h2>
              <p className="text-base text-gray-700">
                The use of this Website by the User, including browsing the Website and availing any Services offered therein is free of cost. The User is only required to pay for the product purchased by the User from the Website. However, the Company reserves the right to amend this no-fee policy and charge the User for any or all services offered / rendered. In such an event, the User will be intimated of the same when he/she attempts to access the Website, and the User shall have the option of declining to avail of the services offered on the Website. Any such change, if made, shall come into effect immediately upon such change being notified to the User, unless specified otherwise.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold mb-2">Mode of Payment</h2>
              <p className="text-base text-gray-700">
                The following payment options are available on the Website:
                <br />a) Domestic and international credit cards issued by banks and financial institutions that are part of the Visa, Master Card & Amex Card networks;
                <br />b) Visa & Master Card Debit cards;
                <br />c) Netbanking/Direct Debit payments from select banks in India. A list of available options will be made available at the time of 'checkout'.
                <br /><br />
                As prescribed by the financial institutions issuing the credit or debit cards affiliated with Visa / Master Card / Amex, the User will required to submit his/her 16-digit card number, card expiry date and 3-digit CVV number (usually on the reverse of the card) while making an online transaction. The User must also have enrolled his/her card with VBV (Verified by Visa) or MSC (MasterCard Secure Code) in order to complete the transaction.
                <br /><br />
                The User is hereby expressly made aware that his/her card statements will reflect that a payment has been made in favour of Gehna Gems India Pvt. Ltd. Third party payment gateways will be used for all services in our site. To place a valid order on the Website, the User is required to complete the transaction, including making payment for the product / services opted for. This may or may not be assisted with a phone call from a customer service representative. By placing an order on the site or over the phone, the User expressly agrees to the terms and conditions and payment policy published in the appropriate section of the Website, or affiliated websites where reference to such affiliated websites has been specifically made.
                <br /><br />
                After the user has added products / services to the shopping cart, and proceeded to the checkout section, the user will be asked for his/her preferred delivery address and other contact information. Once the payment transaction has been successfully completed, the user's order will be processed on receipt of the funds from the user's bank or the credit card company. It is at this stage that the users order is successfully placed. Thereafter the products/ services purchased by the user will be shipped based on the product availability and completion of logistics operations related to the same.
              </p>
            </div>
          </section>

          <section class="emi-policy">
            <h2>EMI</h2>
            <p>Customers can choose any number of Monthly Installments from 2 to 6 months for gold jewelry for product orders above Rs.10,000. This plan is free from interest and processing fees. No documentation required.</p>
            <ul>
              <li>Your product will be booked as per the current market price of gold and will not be affected by the increased gold rate in the market. However, customers will be eligible to receive their orders at a lower gold rate if rates go down.</li>
              <li>Customers will have the flexibility to complete the payment on any given day if you feel the gold rate is best for you.</li>
              <li>On payment of every instalment, you will receive a system-generated mail with product and payment details.</li>
              <li>You will receive your product within 4 days after the payment of your last instalment.</li>
              <li>The product purchased under this plan will be delivered only after all the instalments are paid in full by the customer.</li>
              <li>One installment payment within 31 days from previous payment is compulsory, failing which benefit of the plan will not be applicable and you will be considered as a defaulter for the scheme.</li>
              <li>In case of default in payment of the installment in the stipulated time, the customer will lose the privilege of opting for a lower gold rate besides the gold rate being updated every time it increases till the tenure is completed.</li>
              <li>In case of cancellation, the customer will be charged a 10% of the order value as cancellation fees and the balance amount will be refunded after deducting the cancellation fees within 10 working days from the date of cancellation.</li>
              <li>Orders placed under Gold Rate Protection are eligible for exchange only strictly within 7 days of receipt of the product. Exchanged order will be as per current gold rate prevailing on the website at that time.</li>
              <li>The 7 days Refund Policy is not applicable on any order placed under this scheme.</li>
              <li>Offer applied in the order during booking will remain the same under all circumstances.</li>
              <li>The scheme is applicable only in India. All disputes are subject to the jurisdiction of courts in Bengaluru, Tamil Nadu.</li>
            </ul>
          </section>

          <section class="shipping-policy">
            <h2>SHIPPING POLICY</h2>
           Shipping cost vary on offer Shipping and Gift Packing in India for the jewellery ordered on the Website.Shipping of the product shall be done through Our courier partner BlueDart, Speed Post or any other courier service provider.We provide durable and exclusive tamper-proof packing and deliver it in an exclusive Company labelled box along with the relevant certificates. Delivery dates may differ for different products. At the time of placing the order & checkout, the delivery timeline would be clearly mentioned.Based on the country of import, Our courier partner may need to get customs clearance for Your goods before delivering them to You. Any additional taxes / import duties / customs charges levied by the country of import will be chargeable to the user. The user is liable to reimburse the courier partner for any such charges paid by them on behalf of the user.The Company/ Website reserves the right to release information about the user or their order to local, state, central or international law enforcement officials if required by the law or if authorized by a Court.International Shipping Policy provides for International Shipping Charges as follows:i)Shipping costs are payable for shipping precious jewellery to locations outside India.ii)International orders are normally processed within five (5) business days from the date of the order being placed.iii)Shipping timelines for “made to order/ customized Jewellery” will vary based on the individual product ordered. Shipping timelines will be intimated to the user in advance.iv)All Our products are packed in secure tamper proof packaging. If You find that the package is tampered, please do not accept delivery of the same. If the user accepts delivery, it is be deemed that the product arrived in a tamper proof condition.v)All products ordered in one cart will be shipped to one shipping address. If there is a requirement for the products to be shipped to more than one shipping address then the user shall create separate orders in separate carts for each address.vi)All products are insured by the Company/Website as per Clause 10 (ii).

          </section>

          <section class="exchange-returns">
            <h2>EXCHANGE AND RETURNS</h2>
            <p>Our 7-day return policy gives you time to make sure your purchase is perfect. If you need to return it for any reason, we'll happily provide You with a full refund or exchange, within 7 days of the date of delivery of the order. This is, however, applicable for orders within India only.</p>
            <p>For international orders with international shipping we currently do not accept any returns or exchanges.</p>
          </section>

          <section class="security">
            <h2>SECURITY</h2>
            <p>Transactions on the Website are secure and protected. Any information entered by the User when transacting on the Website is encrypted to protect the User against unintentional disclosure to third parties.</p>
            <p>The User's credit and debit card information is not received, stored by or retained by the Company / Website in any manner. This information is supplied by the User directly to the relevant payment gateway which is authorized to handle the information provided, and is compliant with the regulations and requirements of various banks and institutions and payment franchisees that it is associated with.</p>
          </section>

          <section>
            <div class="security user-obligations-container">
              <h2>User Obligations</h2>
              <p>The User agrees and acknowledges that he/she is a restricted user of this Website, and that he/she:</p>
<br /> <br />
              a) is bound not to cut, copy, distribute, modify, recreate, reverse engineer, distribute, disseminate, post, publish or create derivative works from, transfer, or sell any information or software obtained from the Website. Any such use / limited use of the Website will only be allowed with the prior express written permission of the Company. For the removal of doubt, it is clarified that unlimited or wholesale reproduction, copying of the content for commercial or non-commercial purposes and unwarranted modification of data and information contained on the Website is expressly prohibited.

              <br /> <br />

              b) agrees not to access (or attempt to access) the Website and/or the materials or services by any means other than through the interface provided by the Website. The use of deep-link, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or its content, or in any way reproduce or circumvent the navigational structure or presentation of the Website, materials or any content, or to obtain or attempt to obtain any materials, documents or information through any means not specifically made available through the Website will lead to suspension or termination of the User’s access to the Website, as detailed in Section 11 herein below. The User acknowledges and agrees that by accessing or using the Website or any of the services provided therein, he/she may be exposed to content that he/she may consider offensive, indecent or otherwise objectionable. The Company disclaims any and all liabilities arising in relation to such offensive content on the Website. The User may however report any such offensive or objectionable content, which the Company may then remove from the Website, at its sole discretion.
              <br /> <br />

c) In places where Website permits the User to post or upload data/information, the User undertakes to ensure that such material is not offensive or objectionable, and is in accordance with applicable laws. The User expressly agrees that any such material that is deemed to be objectionable/offensive may be removed from the Website immediately and without notice, and further that the User’s access to the Website may also be permanently revoked, at the sole discretion of the Company.
<br /> <br />


             d)Further undertakes not to:Abuse, harass, threaten, defame, disillusion, erode, abrogate, demean or otherwise violate the legal rights of any other person or entity;Engage in any activity that interferes with or disrupts access to the Website or the services provided therein (or the servers and networks which are connected to the Website);Impersonate any person or entity, or falsely state or otherwise misrepresent his/her affiliation with a person or entity;iv.Publish, post, disseminate, any information which is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever under any law, rule or regulation currently in force; or unlawfully threatening or unlawfully harassing including but not limited to “indecent representation of women” within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;Post any image/file/data that infringes the copyright, patent or trademark of another person or legal entity;Upload or distribute files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of the Website;vii. Download any file posted/uploaded by another User of the Website that the User is aware, or should reasonably be aware, cannot be legally distributed in such a manner;viii. Probe, scan or test the vulnerability of the Website or any network connected to the Website, nor breach the security or authentication measures on the Website or any network connected to the Website. The User may not reverse look-up, trace or seek to trace any information relating to any other user of, or visitor to, the Website, or any other customer of the Website, including any user account maintained on the Website not operated/managed by the User, or exploit the Website or information made available or offered by or through the Website, in any manner;ix. Disrupt or interfere with the security of, or otherwise cause harm to, the Website, systems resources, accounts, passwords, servers or networks connected to or accessible through the Websites or any affiliated or linked websites;x. Collect or store data about other users of the Website.Use the Website or any material or content therein for any purpose that is unlawful or prohibited by these Terms, or to solicit the performance of any illegal activity or other activity which infringes the rights of this Website or any other third party(ies);Violate any code of conduct or guideline which may be applicable for or to any particular product or service offered on the Website;xiii Violate any applicable laws, rules or regulations currently in force within or outside India;xiv Violate any portion of these Terms or the Policy, including but not limited to any applicable additional terms of the Website contained herein or elsewhere, whether made by amendment, modification, or otherwise;xv. Threaten the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order, or cause incitement to the commission of any cognizable offence, or prevent the investigation of any offence, or insult any other nation.xvi. Publish, post, or disseminate information that is false, inaccurate or misleading;xvii. Directly or indirectly offer, attempt to offer, trade, or attempt to trade, any item the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.xviii. Commit any act that causes the Company to lose (in whole or in part) the services of its Internet Service Provider (“ISP”) or in any manner disrupts the services of any other supplier/service provider of the Company/Website;xix. Engage in advertising to, or solicitation of, other users of the Website to buy or sell any products or services not currently displayed on the Website. The User may not transmit any chain letters or unsolicited commercial or junk email/messages to other users via the Website. It shall be a violation of these Terms to use any information obtained from the Website in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to another user of the Website without the express prior written consent of the Company.

             <br /> <br />

The User hereby expressly authorises the Company/Website to disclose any and all information relating to the User in the possession of the Company/Website to law enforcement or other government officials, as the Company may in its sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those involve personal injury and theft / infringement of intellectual property. The User further understands that the Company/Website might be directed to disclose any information (including the identity of persons providing information or materials on the Website) as necessary to satisfy any judicial order, law, regulation or valid governmental request.

<br /> <br />


The User expressly agrees and acknowledges that the Company/Website has no obligation to monitor the materials posted on the Website, but that it has the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms. Notwithstanding this right, the User remains solely responsible for the content of the materials posted on the Website by him/her. In no event shall the Company/Website assume or be deemed to have any responsibility or liability for any content posted, or for any claims, damages or losses resulting from use of any such content and/or the appearance of any content on the Website. The User hereby represents and warrants that he/she has all necessary rights in and to all content provided as well as all information contained therein, and that such content does not infringe any proprietary or other rights of any third party(ies), nor does it contain any libellous, tortuous, or otherwise unlawful or offensive material, and the User hereby accepts full responsibility for any consequences that may arise due to the publishing of any such material on the Website.
<br /> <br />

</div>
          </section>


          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-4">SUSPENSION OF USER ACCESS AND ACTIVITY</h2>
            <div className="space-y-4 text-gray-600">
              <p>Notwithstanding other legal remedies that may be available to it, the Company may in its sole discretion limit the User’s access and/ or activity by immediately removing the User’s access credentials either temporarily or indefinitely, or suspend / terminate the User’s membership, and/or refuse to provide User with access to the Website, without being required to provide the User with notice or cause:</p>
              <ul className="list-disc pl-6">
                <li>If the User is in breach of any of these Terms or the Policy;</li>
                <li>If the User has provided wrong, inaccurate, incomplete or incorrect information;</li>
                <li>If the User’s actions may cause any harm, damage or loss to the other users or to the Website/Company, at the sole discretion of the Company.</li>
              </ul>
            </div>

            <h2 className="text-xl font-semibold text-gray-800 mb-4">INDEMNITY AND LIMITATIONS</h2>
            <div className="space-y-4 text-gray-600">
            The User hereby expressly agrees to defend, indemnify and hold harmless the Website and the Company, its employees, directors, officers, agents and their successors and assigns and against any and all claims, liabilities, damages, losses, costs and expenses, including attorney’s fees, caused by or arising out of claims based upon the User’s actions or inactions, including but not limited to any warranties, representations or undertakings, or in relation to the non-fulfilment of any of the User’s obligations under this Agreement, or arising out of the User’s infringement of any applicable laws, rules and regulations, including but not limited to infringement of intellectual property rights, payment of statutory dues and taxes, claims of libel, defamation, violation of rights of privacy or publicity, loss of service by other subscribers, or the infringement of any other rights of a third party.
<br />
<br />
In no event shall the Company/Website be liable to compensate the User or any third party for any special, incidental, indirect, consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable, and whether or not the Company/Website had been advised of the possibility of such damages, or based on any theory of liability, including breach of contract or warranty, negligence or other tortuous action, or any other claim arising out of or in connection with the User’s use of or access to the Website and/or the products, services or materials contained therein.
<br />
<br />

The limitations and exclusions in this section apply to the maximum extent permitted by applicable law, and the Parties expressly agree that in the event of any statute, rule, regulation or amendment coming into force that would result in the Company/Website incurring any form of liability whatsoever, these Terms and the Policy will stand terminated one (1) day before the coming into effect of such statute, rule, regulation or amendment. It is further agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.
<br />
<br />

               </div>

            <h2 className="text-xl font-semibold text-gray-800 mb-4">INTELLECTUAL PROPERTY RIGHTS</h2>
            <div className="space-y-4 text-gray-600">
              
            Unless expressly agreed to in writing, nothing contained herein shall give the User a right to use any of the Website’s trade names, trademarks, service marks, logos, domain names, information, questions, answers, solutions, reports and other distinctive brand features, save according to the provisions of these Terms. All logos, trademarks, brand names, service marks, domain names, including material, designs, and graphics created by and developed by the Website and other distinctive brand features of the Website are the property of the Company. Furthermore, with respect to the Website created by the Company, the Company shall be the exclusive owner of all the designs, graphics and the like, related to the Website.
<br />
<br />
The User may not use any of the intellectual property displayed on the Website in any manner that is likely to cause confusion among existing or prospective users of the Website, or that in any manner disparages or discredits the Company/Website, to be determined in the sole discretion of the Company.
<br />
<br />

The User is aware that the products displayed on the Website are the artistic creations of the Company/website, and that all intellectual property, including but not limited to copyrights, relating to said products resides with the Company/Website, and that at no point does any such intellectual property stand transferred from the aforementioned creators to the Users. The User is aware that the jewellery designs, blogs and other contents displayed on the website are sole property of the Company and none of the designs and content on the website can copied or reproduced without prior permission of the said owner.
<br />
<br />

The User is further aware that any reproduction or infringement of the intellectual property of the aforementioned owners by the User will result in legal action being initiated against the User by the respective owners of the intellectual property so reproduced / infringed upon. It is agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.
<br />
<br />

 </div>

            <h2 className="text-xl font-semibold text-gray-800 mb-4">DISCLAIMER OF WARRANTIES AND LIABILITIES</h2>
            <div className="space-y-4 text-gray-600"><p>
              
            Except as otherwise expressly stated on the Website, all products/services offered on the Website are offered on an “as is” basis without any warranty whatsoever, either express or implied.b) The Company/Website makes no representations, express or implied, including without limitation implied warranties of merchantability and fitness of a product for a particular purpose. c) The User agrees and undertakes that he/she is accessing the Website and transacting at his/her sole risk and are that he/she is using his/her best and prudent judgment before purchasing any product/service listed on the Website, or accessing/using any information displayed thereon. d) The Website and the Company accepts no liability for any errors or omissions, whether on behalf of itself or third parties, or for any damage caused to the User, the User’s belongings, or any third party, resulting from the use or misuse of any product purchased or service availed of by the User from the Website.e) The Company/Website does not guarantee that the functions and services contained in the Website will be uninterrupted or error-free, or that the Website or its server will be free of viruses or other harmful components, and the User hereby expressly accepts any and all associated risks involved with the User’s use of the Website.f) Our prices are calculated upon the current market value of the precious metal and gem to give the user the best possible value. These prices change from time to time, owing to the fluctuations in prices of precious metal and gem prices.g) Prices on the website are subject to change without notice. The User shall pay the price mentioned against the product bought.h) It is further agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.
            </p> </div>

            <h2 className="text-xl font-semibold text-gray-800 mb-4">SUBMISSIONS</h2>
            <div className="space-y-4 text-gray-600">
              <p>Any comments, ideas, suggestions, initiation, or any other content contributed by the User to the Company or this Website will be deemed to include a royalty-free, perpetual, irrevocable, nonexclusive right and license for the Company to adopt, publish, reproduce, disseminate, transmit, distribute, copy, use, create derivative works, display worldwide, or act on such content, without additional approval or consideration, in any media, or technology now known or later developed, for the full term of any rights that may exist in such content, and the User hereby waives any claim to the contrary. The User hereby represents and warrants that he/she owns or otherwise controls all of the rights to the content contributed to the Website, and that use of such content by the Company/Website does not infringe upon or violate the rights of any third party. In the event of any action initiated against the Company/Website by any such affected third party, the User hereby expressly agrees to indemnify and hold harmless the Company/Website, for its use of any such information provided to it by the User. The Company reserves its right to defend itself in any such legal disputes that may arise, and recover the costs incurred in such proceedings from the User.
              </p>
               </div>

            <h2 className="text-xl font-semibold text-gray-800 mb-4">DISPUTE RESOLUTION AND JURISDICTION</h2>
            <div className="space-y-4 text-gray-600">
              <p>
              It is expressly agreed to by the Parties hereto that the formation, interpretation and performance of these Terms and any disputes arising here from will be resolved through a two-step Alternate Dispute Resolution (“ADR”) mechanism. It is further agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.
<p>

a) Mediation: In case of any dispute between the parties, the Parties will attempt to resolve the same amicably amongst themselves, to the mutual satisfaction of both Parties. In the event that the Parties are unable to reach such an amicable solution within thirty (30) days of one Party communicating the existence of a dispute to the other Party, the dispute will be resolved by arbitration, as detailed herein below;
</p>
<p>

b) Arbitration. In the event that the Parties are unable to amicably resolve a dispute by mediation, said dispute will be referred to arbitration by a sole arbitrator to be appointed by the Company, and the award passed by such sole arbitrator will be valid and binding on both Parties. The Parties shall bear their own costs for the proceedings, although the sole arbitrator may, in his/her sole discretion, direct either Party to bear the entire cost of the proceedings. The arbitration shall be conducted in English, and the seat of Arbitration shall be the city of Bengaluru in the state of Tamil Nadu, India.
</p>
<p>

The Parties expressly agree that the Terms, Policy and any other agreements entered into between the Parties are governed by the laws, rules and regulations of India, and that the Courts at Bengaluru shall have exclusive jurisdiction over any disputes arising between the Parties.
</p>

              </p>
                </div>

            <h2 className="text-xl font-semibold text-gray-800 mb-4">NOTICES</h2>
            <div className="space-y-4 text-gray-600">
              <p>Any and all communication relating to any dispute or grievance experienced by the User may be communicated to the Company by the User reducing the same to writing, and sending the same to the registered office of the Company by Registered Post Acknowledgement Due / Speed Post Acknowledgement Due (RPAD / SPAD)              </p>
            </div>

            <h2 className="text-xl font-semibold text-gray-800 mb-4">MISCELLANEOUS PROVISIONS</h2>
            <div className="space-y-4 text-gray-600">
              <p><strong>a) Entire Agreement:</strong> These Terms, read with the Policy form the complete and final contract between the User and the Company with respect to the subject matter hereof and supersedes all other communications, representations and agreements (whether oral, written or otherwise) relating thereto;              </p>
              <p><strong>b) Waiver:</strong> The failure of either Party at any time to require performance of any provision of these Terms shall in no manner affect such Party’s right at a later time to enforce the same. No waiver by either Party of any breach of these Terms, whether by conduct or otherwise, in any one or more instances, shall be deemed to be or construed as a further or continuing waiver of any such breach, or a waiver of any other breach of these Terms.              </p>
              <p><strong>c) Severability:</strong> If any provision/clause of these Terms is held to be invalid, illegal or unenforceable by any court or authority of competent jurisdiction, the validity, legality and enforceability of the remaining provisions/clauses of these Terms shall in no way be affected or impaired thereby, and each such provision/clause of these Terms shall be valid and enforceable to the fullest extent permitted by law. In such case, these Terms shall be reformed to the minimum extent necessary to correct any invalidity, illegality or unenforceability, while preserving to the maximum extent the original rights, intentions and commercial expectations of the Parties hereto, as expressed herein.</p>
            </div>
          </section>



        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;